Deploy test 30

diff --git a/.github/workflows/hello.yml b/.github/workflows/hello.yml
--- a/.github/workflows/hello.yml
+++ b/.github/workflows/hello.yml
@@ -9,7 +9,7 @@ on:
 jobs:
   CD:
     name: createImageNginx
-#    needs: SonarCloud
+    needs: SonarCloud
     env: 
       SSH_TO_SCS: ${{ secrets.SSH_TO_SCS }}
     runs-on: ubuntu-latest
@@ -28,48 +28,40 @@ jobs:
       - name: Deploy
         run: 
           ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /home/runner/.ssh/id_rsa scstuff@83.172.42.34 'cd /scs && 
-          echo "text1" && 
           tar -xzvf front.tar.gz &&
           echo "FROM nginx" > dockerfile &&
           echo "COPY ./front /usr/share/nginx/html" >> dockerfile &&
-          echo "text2" &&
           eval $(minikube docker-env) &&
-          echo "text3" &&
-          docker build -t nginx:latest . &&
-          echo "text4" &&
-          export DOCKER_IMAGE_NAME="nginx:latest" &&
-          echo "text5" &&
+          docker build -t scsnginx:latest . &&
+          export DOCKER_IMAGE_NAME="scsnginx:latest" &&
           envsubst < template-nginx-deployment > nginx-deployment.yaml &&
-          echo "text6" &&
           kubectl apply -f nginx-deployment.yaml &&
-          echo "text7" &&
           eval $(docker-machine env -u) &&
-          echo "text8" &&
-          kubectl rollout restart deployment nginx-deployment's
-#  sonarcloud:
-#    name: SonarCloud
-#    runs-on: ubuntu-latest
-#    steps:
-#      - uses: actions/checkout@v3
-#        with:
-#          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
-#      - name: SonarCloud Scan
-#        uses: SonarSource/sonarcloud-github-action@master
-#        env:
-#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
-#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-#      - name: SonarCloud_Status
-#        run: |
-#          branch_name=${GITHUB_REF#refs/heads/}
-#          sonar_response=$(curl -s "${api_url}?projectKey=${project_key}&branch=${branch_name}")
-#          status=$(echo $sonar_response | jq -r '.projectStatus.status')
-#          if [ "$status" = "OK" ] || [ "$status" = "WARN" ] ; then
-#            echo "Analysis completed successfully."
-#            echo "https://sonarcloud.io/summary/new_code?id=${project_key}&branch=${branch_name}"
-#          else
-#            echo "Analysis failed or status is not successful."
-#            echo "https://sonarcloud.io/summary/new_code?id=${project_key}&branch=${branch_name}"
-#            exit 1
-#          fi
+          kubectl rollout restart deployment nginx-deployment'
+  sonarcloud:
+    name: SonarCloud
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+      - name: SonarCloud Scan
+        uses: SonarSource/sonarcloud-github-action@master
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      - name: SonarCloud_Status
+        run: |
+          branch_name=${GITHUB_REF#refs/heads/}
+          sonar_response=$(curl -s "${api_url}?projectKey=${project_key}&branch=${branch_name}")
+          status=$(echo $sonar_response | jq -r '.projectStatus.status')
+          if [ "$status" = "OK" ] || [ "$status" = "WARN" ] ; then
+            echo "Analysis completed successfully."
+            echo "https://sonarcloud.io/summary/new_code?id=${project_key}&branch=${branch_name}"
+          else
+            echo "Analysis failed or status is not successful."
+            echo "https://sonarcloud.io/summary/new_code?id=${project_key}&branch=${branch_name}"
+            exit 1
+          fi
           
           
